#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQ6/1LNyEu/5TCq616dpoCeuqxDsSsXNO9yJU+GvlbK8CMoNGLHs/VxeL9rTIsNXUEO8h9Wbyz0kTfd1isicS9hc5455mtxrKE1UYI59AlgH4gbM2J5N2ewfrJ1VdVIlILnuu2bIwOZTDBZj3foR+0s45be2pUy65rpqq95iHJcapxcWt0AoAEVQnMlLcSRL+UmGvX6RCVH4zOHzuP0HBvVhnwp2at2SSwEOLRzb899y0uPWM5DaxefbDHji6ZgPu+SHFaHH9bKuWjvb9ZMDDomf2cPkuR5JEnv6stR5laH/kiI+zpVRMRpIG6qUfc8F7J8VgfFzCo7Ekgh1J7d5Gd cameron@vostok
